### PR TITLE
Add new properties for Histogram and layout.Axis

### LINKED ISSUE #431: Add some properties for Axis and Histogram
Hello @alexarchambault ,

I am in the need of some new properties:

- Histogram.{yaxis, hovertext}
- layout.Axis.{tickformat, fixedrange} 

I will create a pull request and would be very happy, if you could create a new release with it.

Thanks in advance,
  Sven

### PR DESCRIPTION
**Pull request by sven42**
This fixes #431.

Furthermore:
- Adds a demo for a basic histogram and a styled basic histogram using these new properties.
- Adds the following methods to plotly.Plotly:
  - react()
  - relayout()
  - prune()
  - validate()
- Updates dependencies, plugins and sbt

Best regards,
  Sven

### CODE REVIEW

**Comment by sbrunk** [comment]
Looks good to me.

@alexarchambault are you ok with me merging this and cutting a `v0.8.5` release afterwards? The release should work automated from CI after tagging with the `sbt-ci-release` right? I haven't done it yet in this repo though so I want to check with you first.

**Comment by alexarchambault** [comment]
@sbrunk Sure, go ahead. Feel free to review / merge things as you feel in this repo.

**Comment by sbrunk** [comment]
Uh, seems like there's some issue with publishing due to a missing pgp key: https://github.com/alexarchambault/plotly-scala/actions/runs/9061691273/job/24894080970
Perhaps you have to trigger the publishing job @alexarchambault?

**Comment by alexarchambault** [comment]
@sbrunk I just updated the secrets, that [seems to have fixed it](https://github.com/alexarchambault/plotly-scala/actions/runs/9128511829/job/25101015237)

**Comment by sbrunk** [comment]
Thanks @alexarchambault!

**Pull request merged**
