### PR TITLE
Adding Heatmap trace implementation

### PR DESCRIPTION
**Pull request by eric-czech**
Hi @alexarchambault, thank you for your work on this project!  I love how you've structured it.

I wanted to get more familiar with it by adding Heatmaps and I think this is a solid start.  Let me know if I missed anything, but this PR includes:

- Additions to ```Trace.scala``` for Heatmaps
- Necessary changes in the argonaut codec class to support new parameters, namely colorscale serialization
- Examples in the Demo
- New tests in DocumentationTests to force decoding of all the Plot.ly heatmap examples

I also needed to make a few minor tweaks to the ```make-ghpages.sh``` script in order to test that the demos are still being rendered correctly.

Lastly, I also needed to update plotly-documentation to correct some errors in the JS examples.  How would you suggest I commit that back to your fork?  Here's the patch for the diff: [plotly-documentation.patch.txt](https://github.com/alexarchambault/plotly-scala/files/4014618/plotly-documentation.patch.txt).  There's not much to it beyond a typo and some parameters that are supposed to be on the main layout rather than an axis.

Thanks again!

### CODE REVIEW

**Comment by eric-czech** [comment]
FYI it looks like everything cleared on Travis except the plotly-documentation fixes I mentioned (not sure how to get them upstream for the build).

Also, I'd like include a way to propagate nulls but they're being replaced somewhere in the encoding process.  This might be better left to a separate PR/issue, but do you know off the top of your head how to make this work?

```scala
Heatmap(
    z=Seq(
        Seq(10, null.asInstanceOf[Int]), 
        Seq(10, null.asInstanceOf[Int])
    ),
    x=Seq("Yes", "No"),
    y=Seq("Morning", "Evening"),
).plot()
```
(The cells on the right should be blank instead of 0, like in https://plot.ly/javascript/heatmaps/#heatmap-with-categorical-axis-labels)

Screen Shot 2020-01-02 at 6 03 39 AM

**Comment by alexarchambault** [comment]
Thanks a lot, that looks neat!

I just pushed a commit (https://github.com/alexarchambault/plotly-documentation/commit/eae136bb920c7542654a5e13cff04a0de175a08d) in the fork of plotly-documentation used as a submodule here, based on your patch.

Check it out from the `plotly-documentation` directory, and add the updated submodule from the plotly-scala repo (something like `cd plotly-documentation && git fetch origin && git checkout eae136b && cd .. && git add -- plotly-documentation` should do). That ought to make the tests pass.

**Comment by alexarchambault** [comment]
About the `null`s, I think they could be supported either by adding an extra conversion from `Seq[Seq[Option[Int]]]` (I think argonaut will render that as either integers or `null`s), and / or adding a conversion from `Seq[Seq[Integer]]`, which are fine with null values. In the former case, users would pass values like `Seq(Seq(None, Some(2), Some(3)))`. In the latter case, they would pass `Seq(Seq[Integer](null, 2, 3))` (explicit `[Integer]` required).

**Comment by eric-czech** [comment]
Awesome, thanks for committing that!  That makes sense with the nulls too -- I may try to tackle that with one of those approaches if it starts to chafe a little more but for now I'll leave this PR as-is.  Looks like it's all clear now.

**Comment by alexarchambault** [comment]
Merging, thanks @eric-czech!

**Pull request merged**
